# Generated by Django 6.0.2 on 2026-03-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPIExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.TextField()),
                ('campaign_id', models.CharField(default='demo_campaign', max_length=255)),
                ('campaign_name', models.CharField(blank=True, default='', max_length=255)),
                ('campaign_type', models.CharField(default='general', max_length=255)),
                ('file_path', models.CharField(max_length=1000)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('execution_output', models.TextField(blank=True, default='')),
                ('kpi_payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
