# Generated by Django 6.0.1 on 2026-03-08 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(help_text='Campaign ID in the LeaCall system.', max_length=128)),
                ('campaign_name', models.CharField(blank=True, max_length=255)),
                ('campaign_type', models.CharField(choices=[('marketing', 'Marketing'), ('sav', 'SAV'), ('vente', 'Vente'), ('other', 'Autre')], default='other', max_length=16)),
                ('api_endpoint', models.CharField(blank=True, help_text="LeaCall API endpoint for this campaign's data. Leave blank to use the default: /api/campaigns/{campaign_id}/contacts/", max_length=512)),
                ('record_id_field', models.CharField(default='id', help_text='Name of the unique-ID field in LeaCall records.', max_length=128)),
                ('field_mapping', models.JSONField(blank=True, default=dict, help_text='{"leacall_field": "Display Name"} — empty means keep original names.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['client', 'campaign_name'],
                'unique_together': {('client', 'campaign_id')},
            },
        ),
        migrations.CreateModel(
            name='ETLRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_count', models.PositiveIntegerField(default=0)),
                ('transformed_count', models.PositiveIntegerField(default=0)),
                ('loaded_count', models.PositiveIntegerField(default=0)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etl_runs', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='ETL.clientdatasource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ETLRawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ETL.etlrun')),
            ],
            options={
                'ordering': ['row_index'],
                'unique_together': {('run', 'row_index')},
            },
        ),
        migrations.CreateModel(
            name='CampaignRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leacall_record_id', models.CharField(help_text='Original record ID from the LeaCall system.', max_length=255)),
                ('data', models.JSONField(default=dict, help_text='Dynamic key/value pairs extracted from the campaign.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ETL.clientdatasource')),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_records', to='ETL.etlrun')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('data_source', 'leacall_record_id')},
            },
        ),
    ]
