# Generated by Django 6.0.1 on 2026-03-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_enabled_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='leacall_api_key',
            field=models.CharField(blank=True, default='', help_text="Clé API pour s'authentifier auprès du serveur LeaCall.", max_length=512),
        ),
    ]
